import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links = [
  {
    href: '/',
    label: 'Home',
  },
  {
    href: '/docs',
    label: 'Docs',
  },
  {
    href: '/todos',
    label: 'Todos',
  },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en-CA">
      <body className={`${inter.className} p-10 h-screen w-screen`}>
        <header className="mb-20">
          <nav>
            <ul className="flex items-center">
              {links.map((link) => (
                <li key={link.href} className="px-4 text-2xl">
                  <Link href={link.href}>{link.label}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        <div>{children}</div>
      </body>
    </html>
  )
}
